
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('articles').del()
    .then(function () {
      // Inserts seed entries
      return knex('articles').insert([
        { title: 'Soccer', urltitle: 'Soccer', author: 'Lionel', body: 'Upper 90 World Cup hat trick number 10 referee goalie yellow card three-five-two forward UEFA European Championship striker midfielder soccer pitch red card. Three-five-two defender goal brace UEFA European Championship hat trick chip one-two midfielder red card pitch goalie four-four-two yellow card African Cup of Nations. Striker African Cup of Nations referee upper 90 ball one-two hat trick brace midfielder halftime goal pitch three-five-two red card chip. Hat trick center-half forward referee three-five-two World Cup soccer defender midfielder pitch ball goalie African Cup of Nations brace number 10.' },
        { title: 'Gangsters', urltitle: 'Gangsters', author: 'G.E.T.O', body: 'Lorizzle ipsizzle shiz bow wow wow boom shackalack, consectetuer adipiscing my shizz. Nullizzle sapien velizzle, aliquet volutpat, fo shizzle quis, izzle stuff, check it out. The bizzle shit tortizzle. Sizzle erizzle. Break it down gizzle dolor dapibizzle turpis brizzle shiz. Maurizzle check out this bow wow wow et turpizzle. You son of a bizzle in tortor. Pellentesque da bomb rhoncizzle daahng dawg. Rizzle tellivizzle habitasse fo shizzle for sure. Bow wow wow dapibizzle. Hizzle tellizzle urna, pretizzle eu, mattis shiznit, eleifend vitae, fizzle. Phat yo mamma. Integer sempizzle velizzle tellivizzle break yo neck, yall.' },
        { title: 'Cats', urltitle: 'Cats', author: 'Nyan', body: "Nya nya nyan. Where is my slave? I'm getting hungry knock dish off table head butt cant eat out of my own dish for cat dog hate mouse eat string barf pillow no baths hate everything or my slave human didn't give me any food so i pooped on the floor so headbutt owner's knee for a nice warm laptop for me to sit on, cat cat moo moo lick ears lick paws. Somehow manage to catch a bird but have no idea what to do next, so play with it until it dies of shock lick face hiss at owner, pee a lot, and meow repeatedly scratch at fence purrrrrr eat muffins and poutine until owner comes back what a cat-ass-trophy! or eat an easter feather as if it were a bird then burp victoriously, but tender for jump around on couch, meow constantly until given food, but scratch sleep. Tuxedo cats always looking dapper put butt in owner's face so your pillow is now my pet bed meow kitten is playing with dead mouse, you are a captive audience while sitting on the toilet, pet me roll over and sun my belly. I like frogs and 0 gravity chase imaginary bugs, soft kitty warm kitty little ball of furr for stare at ceiling light purr while eating. " },
        { title: 'Bacon', urltitle: 'Bacon', author: 'Bacon God 808', body: "Bacon ipsum dolor amet ground round bresaola ribeye tail picanha salami pastrami jowl shoulder tri-tip prosciutto cupim. Ground round pork ham hock capicola cow jerky buffalo. Sausage pork chop ham hock, prosciutto kevin brisket flank spare ribs swine venison filet mignon t-bone landjaeger. Ham meatball jerky spare ribs pork loin, fatback ball tip drumstick sausage cow boudin. Pork belly corned beef burgdoggen t-bone. Brisket kevin andouille tongue leberkas bacon chuck ball tip beef ribs." }
      ]);
    });
};
